### ISSUE TITLE
[Feature] Add templates for Issues and Pull Requests

### ISSUE THREAD

**Issue by kailash360** [EOS-uiux-Solutions/strapi#25]
Currently in the repository, there are no templates for creating issues and making pull requests.
It would be better if these templates are added in the project. They can benefit by maintaining a consistent structures of issues and pull requests, extracting more details and necessary information from the user.

I want to work on this.

**Comment by StarTrooper08** [comment]
Can I do it?

**Comment by atharvashirdhankar** [comment]
Can I help here?
